export const GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST' = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS' = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED: 'GET_CATEGORIES_FAILED' = 'GET_CATEGORIES_FAILED';
export const CHANGE_DISPLAY_CATEGORIES: 'CHANGE_DISPLAY_CATEGORIES' = 'CHANGE_DISPLAY_CATEGORIES';