export const GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST' = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS' = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED: 'GET_PRODUCTS_FAILED' = 'GET_PRODUCTS_FAILED';

export const INCREMENT_PRODUCT_COUNT: 'INCREMENT_PRODUCT_COUNT' = 'INCREMENT_PRODUCT_COUNT'
export const DECREMENT_PRODUCT_COUNT: 'DECREMENT_PRODUCT_COUNT' = 'DECREMENT_PRODUCT_COUNT'